FROM node:9.4

COPY . ./

ENV FSRUSERNAME=""
ENV FSRPASSWORD=""
ENV HUBOT_ALIAS=""
ENV HUBOT_FORECAST_API_KEY=""
ENV HUBOT_GOOGLE_CSE_ID=""
ENV HUBOT_GOOGLE_CSE_KEY=""
ENV HUBOT_SLACK_TOKEN=""
ENV HUBOT_WEATHER_CELSIUS=""
ENV HUBOT_MAINTAINERS=""
ENV CLARIFAI_ID=""
ENV CLARIFAI_SECRET=""

RUN npm install

ENTRYPOINT ["./bin/hubot"]
CMD ["-a", "slack"]
