# Description:
#   Such porn, much wow
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   hubot porn me - Get a random porn title
#
# Author:
#   Johnny Deep


module.exports = (robot) ->
  robot.respond /porn (.+)/i, (msg) ->
    porn_title = msg.random porn_responses

    name = msg.match[1]
    if name == "me"
        porn_title = porn_title.replace("{target}", msg.message.user.name.capitalize())
    else
        porn_title = porn_title.replace("{target}", name.capitalize())

    msg.send porn_title


porn_responses = [
        "11.000 Ruten",
        "12 Schwedinnen in Afrika",
        "2 x 2 im Himmelbett",
        "2001 Orgien im Weltraum",
        "69 Liebesspiele",
        "69 - Vorspiel zur Ekstase",

        "Ach, blas mir doch mal einen Marsch",
        "Ach jodel mir noch einen - Stoßtrupp Venus bläst zum Angriff",
        "Alfreds unheimliche Begegnung mit der Reizwäsche",
        "Alle Kätzchen naschen gern",
        "Alpenglühn im Dirndlrock",
        "Als die Frauen noch Schwänze hatten",
        "Arschibald, der Porno-Butler",
        "Auch Engel baden manchmal nackt",
        "Auch Fummeln will gelernt sein",
        "Auch Ninotschka zieht ihr Höschen aus",
        "Auf der Alm, da gibt's koa Sünd'",
        "Auf und nieder - ich könnt schon wieder",
        "Aufruhr im Frauengefängnis",
        "Die Auto-Nummer - Sex auf Rädern",

        "Akte Wixx",
        "Al Caporno",
        "Alarm im Darm",
        "Alice im Ständerland",
        "Aliens vs. Penetrator",
        "American Fistory XXX",
        "American Fickboxer",
        "Analdin und die wunde Schlampe",
        "Analgeddon",
        "Analstufe Rot",
        "Analritter 2 - Heute wird eingedost",
        "Andere Länder, andere Titten",
        "Animal Farm - Jetzt ficken wir Tiere",
        "Arielle, die Nicht-mehr-Jungfrau",
        "Auf den Highway sind die Schlampen los",
        "Auf der Liege der außergewöhnlichen Gentlemen",
        "Aufstand in der Lederhose",
        "Axel Fick und Obel Wichs",

        "Bademeister-Report",
        "Banana Airlines - Die verrückteste Lustlinie der Welt",
        "Baron Porno's nächtliche Freuden",
        "Beim Jodeln juckt die Lederhose",
        "Bohr weiter, Kumpel",
        "Bombenstimmung im Hauptquartier",
        "Bora Bora",
        "Die Bruchpiloten vom Königssee",
        "Brummi, sein Kolben läuft auch ohne Diesel",
        "Das Bullenkloster",
        "Das bumsfidele Heiratsbüro",
        "Die bumsfidelen Mädchen vom Birkenhof",
        "Die Bumsköpfe",
        "Der Bumsladen-Boß",

        "Bambi im Land der geilen Böcke",
        "Bananenfick in Mosambik",
        "Battlefield Ass",
        "Beischlafes Bruder",
        "Beverly Hills Cock",
        "Big Mama - Speckfalten in Wallung",
        "Bitch - Der Fickdoktor",
        "Black Cock Down",
        "Blair Bitch Project",
        "Blowing for Columbine",
        "Bonnie in Clyde",
        "Boschwanza",
        "Baffy, die Dildojägerin",
        "Deutschland sucht den Pornstar",
        "Bienenstich im Lesbennest",

        "Cockduel",
        "Cocklateral damage",
        "Cockzilla, Ein Riesenschwanz in New York",
        "Chinese Dickstory (1-3)",

        "Des Satans heiße Katzen",
        "Die Deutsche Sex-Partei",
        "Django Nudo und die lüsternen Mädchen von Porno Hill",
        "Donnerwetter! Donnerwetter! Bonifatius Kiesewetter",
        "Ein Doppeldecker für Madame O.",
        "Dornwittchen und Schneeröschen",
        "Down Town - Die nackten Puppen der Unterwelt",
        "Dr. Fummel und seine Gespielinnen",
        "Dr. Jeckel und Miss Hide",
        "Dralle Brüste, steile Schenkel",
        "Drei Schwedinnen in Oberbayern",
        "Drüber, drunter und drauf",

        "Das Besteigen der Lämmer",
        "Das fickende Klassenzimmer",
        "Das Sexperiment",
        "Das Todessperma des Dr. Mabumsen",
        "Das Wunder im Bernd",
        "Der Club der roten Fister",
        "Der Herr der Cockringe",
        "Der große Ficktator",
        "Der Name der Hose",
        "Der Mönch mit der Peitsche",
        "Der Pimmel über Berlin",
        "Der Sexorzist",
        "Deutschland sucht den Superficker",
        "Die Fickinger",
        "Die Prinzessin auf der Eichel",
        "Die Unbesteigbaren von hinten geknallt",
        "Die Vögler",
        "Drei Schwengel für Charlie",
        "Dr. Jekyll in Mrs. Hyde",
        "Dornmöschen",
        "Dune der Brüsteplanet",
        "Dickman Begins",
        "Dickman (1+2)",
        "Dickman& Robin",
        "Domina Day",

        "Ehemänner-Report",
        "Ehepaar sucht Gleichgesinntes",
        "Das ehrliche Interview - Die sexuellen Wünsche der Frau von heute",
        "Eine nach der anderen - Laß fummeln, Puppe",
        "Er war besonders wertvoll für die Damen - Ein echter Hausfrauenfreund",
        "Erotik im Beruf - Was jeder Personalchef gern verschweigt",
        "Die erotischen Abenteuer der drei Musketiere",
        "Es war nicht die Nachtigall",

        "Edward mit den Penishänden",
        "Ein Fuck kommt selten Alleine",
        "Es wird geschluck was in den Mund kommt",
        "Eine für alle, alle in einer",

        "Facts - Kopenhagen-Sex-Report",
        "Fans - Fans - Fans - Runter mit den Pants",
        "Flesh Gordon - Schande der Galaxis",
        "Das französische Frühstück",
        "Frau Professor kann's noch besser",
        "Frisch, fromm, fröhlich, frei",
        "Die fröhlichen Holzfäller der nickenden Fichten",
        "Fummeln im Wasser macht immer nasser",

        "Fäkalschlacht am Analschacht",
        "Feucht und Feuchter 2 - jetzt wirds spritzig",
        "Feuchte Schenkel im Cockpit",
        "Fick-Bonbons - Jetzt wirds feucht im Mund",
        "Fickendes Inferno",
        "Ficket Nemo",
        "Ficki und die starken Männer",
        "Fickhof der Muschitiere",
        "Fist Club",
        "Flesh Gordon",
        "Flucht von Analtraz",
        "Fuck Bill",
        "Fuck me if you can",
        "Fuck off - Im Körper des Feindes",
        "Fummeln im Sturm (1-6)",
        "Fuckzilla",
        "Ficky Mouse - Gay Crazy",

        "Geh, zieh dein Dirndl aus",
        "Gejodelt wird im Unterhöschen",
        "Die goldene Banane von Bad Porno",
        "Graf Porno bläst zum Zapfenstreich",
        "Graf Porno und die liebesdurstigen Töchter",
        "Graf Porno und seine Mädchen",
        "Greta, die Fremde, kam nackt",
        "Grimms Märchen von lüsternen Pärchen",
        "Grüne Witwen - billig zu haben",

        "Gaylien - Director's Fuck",
        "Gaywatch, Die Riesenschwänze von Malibu",
        "Gay's Anatomy",

        "Haben Sie Interesse an der Sache?",
        "Hänsel und Gretel verliefen sich im Wald",
        "Hattu Keuschheitsgürtel muttu knabbern",
        "Heiße Semesterferien",
        "Hemd hoch oder ich schieße!",
        "Hurra, die Schwedinnen sind da",

        "Harte Spiele",
        "Hairy Popper und der Gefangene von Arschpackan",
        "Hairy Popper und der Stab der Steifen",
        "Hairy Popper und die Kammer des Schleckens",
        "Hairy Popper und der Feuerfick",
        "Hairy Popper und der Orgasmus des Phoenix",
        "Hairy Popper und der Vollblutfick",
        "Heisse Länder - Dauerständer",
        "Helicoptermann 2 - 'Die Rückkehr des Kreiselfickers'",
        "HELLRASIERT",
        "Herr der Penisringe",
        "Highway to Möpse",
        "Hitchhikers guide to the fucktasy",
        "Hotel Sodom - Analstufe Rot",
        "House of Wixx",
        "Hör mal wer da nagelt",

        "I need - Ich hab's nötig",
        "Ich - Das Abenteuer, heute eine Frau zu sein",
        "Ich fühl' es kommen",
        "In 80 Betten um die Welt",

        "I, Fickbot",
        "Ich war jung und brauchte das Geld",
        "Ich weiß wer dich letzen Sommer gefickt hat",
        "Ich weiß noch immer wer dich letzten Sommer gefickt hat",
        "Ich werde immer wissen wer dich letzten Sommer gefickt hat",
        "In 80 Tagen durch ganz Hinterfeld",
        "In einem Loch vor unserer Zeit",
        "Inspektor Clouseau — Der beste Mann von Interpo",
        "Im Land der RaketenSpermer",
        "Im Wald und auf der Heidi 1-3",
        "Im Wald wird hart geknallt",
        "Im Kloster der 1000 Sünden",
        "Independence Gay",
        "In Diana Jones",
        "Inzestbauern vom Rammlerhof",
        "iPop",

        "Jack the Raper",
        "Jane Blond - Casino Anal",
        "Jane Blond - Goldficker",
        "Jane Blond - Der Arsch ist nicht genug",
        "Jane Blond - Der Mann mit dem goldenen Schwanz",
        "Jane Blond - Im Angesicht des Kotes",
        "Jane Blond - Moonshaver",
        "Jane Blond - Der Spion mit dem ich Liebe machte",
        "Jarhead - Willkommen im Bett",
        "Jeanne d'Arsch",
        "Jetzt bin ich alt und brauch immer noch Geld",
        "Jurassic Porn",

        "Ein Kaktus ist kein Lutschbonbon",
        "Der kleine Dicke mit dem großen Langen",
        "Köpfchen in das Wasser, Schwänzchen in die Höh'",
        "Kreuzberger Liebesnächte",

        "Kack ab Baby 2",
        "Kapitän Arsch und seine geilen Piraten",
        "Kaviar zum Frühstück",
        "Kevin allein im Puff",
        "King Dingeling und die blonde Frau",
        "Kompanie Huren 2: Trommelfeuer aus der Sackkanone",
        "König der Mösen",
        "Kuck' mal wer da schluckt!",
        "Kung Fu Fisting",

        "Laß jucken im Heu",
        "Laß jucken, Kumpel",
        "Laß jucken, Kumpel 3. Teil - Maloche, Bier und Bett",
        "Laß knacken Schätzchen - Gauner der Liebe",
        "Laß laufen Kumpel",
        "Laß uns Doktor spielen",
        "Die letzte amerikanische Jungfrau",
        "Liebe durch die Autotür",
        "Liebe durch die Hintertür",
        "Liebe in drei Dimensionen",
        "Liebesgrüße aus der Lederhose 6. Teil - Eine Mutter namens Waldemar",
        "Liebesgrüße aus der Lederhose VII - Kokosnüsse und Bananen",
        "Lolita am Scheideweg",
        "Lustvoll eine Schlange streicheln",

        "Lass die Enkel zwischen die Schenkel",
        "Lawrence von Analien",
        "Liebling, ich habe die Kinder gefickt",
        "Last Penis Standing",

        "Mädchen, die am Wege liegen",
        "Mädchen, die nach München kommen",
        "Mädchen, die sich hocharbeiten",
        "Mädchen, die sich selbst bedienen",
        "Mädchen in der Rückenlage",
        "Das Mädchen Julius",
        "Mei Hos' ist in Heidelberg geblieben",
        "Mutti, Mutti, er hat doch gebohrt",

        "Mad Maxxx auf Tinas Donnerkuppeln",
        "Mac Geiler",
        "Mann fickt Hund",
        "Maria mag die Lena",
        "Marry Poppins",
        "Mighty Fucks",
        "Mighty Fucks II - Die Superficker kehren zurück",
        "Moby Fick - Im Arsch des Pottwals",
        "Monstergurken überfallen die Schweiz",
        "Monsters Of Cock - Das Schwanzfestival",

        "Nach Stockholm der Liebe wegen",
        "Der nächste Herr - dieselbe Dame",
        "Nackt unter Kannibalen",

        "Nackt Zerhackt und Angekackt",

        "Ob Dirndl oder Lederhos', gejodelt wird ganz wild drauflos",
        "Oben ohne, unten Jeans",
        "Oben ohne - unten nix",
        "Der Ostfriesen-Report: O mei, haben die Ostfriesen Riesen",

        "Oma, fick mich ins Koma",
        "Oma Rose \"98\" fickgeil und nicht tot zukriegen",
        "One Night in Bangckock",
        "One Night in Paris",
        "One Night in Rüsseldorf",
        "Operation Delta Fick I- III",
        "Oral! Oral! Oral!",

        "Penispiraten auf Rektalrandale",
        "Per Anhalter durch den Analfick",
        "Peterchens Wichsfahrt",
        "Petri Geil! Angelurlaub am Analsee",
        "Pipi auf Karl-Heinz",
        "Pipi im Puller-Puller-Land",
        "Pissing in Action",
        "Pulp Fickschön",
        "Popeye, der Puffbesitzer",
        "Porn Wars Periode I - Die dunkelbraune Bedrohung",
        "Porn Wars Periode II - Anschiss der Klokrieger",
        "Porn Wars Periode III - Die Rache der Spermien",
        "Porn Wars Periode IV - Ein neuer Harem",
        "Porn Wars Periode V - Das Spermium schlägt zurück",
        "Porn Wars Periode VI - Die Rückkehr der Analritter",

        "Quasimodo und seine sieben Glocken",

        "Rate mal wer beim Essen kommt",
        "Reinstecke Fuchs",
        "Rex Dildo - Arschalarm auf der Akropolis",
        "Robin Cock - König der Stecher",
        "RoboCock",
        "Roundhouse Fick - Chuck im Rausch der Leidenschaft",

        "Schwedenmädel in Paris",
        "Seid nett aufeinander",
        "Sexplosiv",
        "Siegfried und das sagenhafte Liebesleben der Nibelungen",
        "Stoßverkehr",
        "Stoßzeit - Rush Hour",

        "Sauerei auf der Bounty",
        "Schamlos in Seattle",
        "Scheidi und der Einöli",
        "Scheiß am Stil",
        "Schneeflittchen und die sieben Geilen",
        "Schwanz der Vampire",
        "Schwänzel und Gretel",
        "Schwänze & Partner",
        "Schweinchen Fick",
        "SEX AGE 2 -jetzt wird gespritzt",
        "Sexcalibur",
        "Sexy Island - Der Kampf ums nackte Überleben",
        "Sexy Pirates - Hier wird nicht nur in See gestochen",
        "Shaving Private Ryan",
        "Shaving Ryan's Privates",
        "Sieben Tage, sieben Möpse",
        "Sklave Pupsmuckel und der geile Meister Leder",
        "Spermarella und die sieben Bukkakezwerge",
        "Spermboat Willie",
        "Sponge Bob Arschkopf",
        "Spiel mir am Glied mit Kot",
        "Stadt der Engen",
        "Stanley Kuhficks - Cockwork Orange",
        "Starfick - Popisode 1:\"Das Impedium fickt zurück\"",
        "Steven Strings - Shiting",
        "Stoß langsam I- III",
        "Sündbart der Seepfarrer",
        "Swingapur",

        "Texas Chainfuck Massacre",
        "Tatsächlich ... Lesben",
        "The Ass-Team",
        "The Gay after Tomorrow",
        "The Gays's After",
        "The Masturbator",
        "The Oklahoma bumser",
        "The Porn Identity",
        "The Texas Dildo Massacre",
        "The Truman Po",
        "Tokiobordel",
        "Totgefickt am 4. Juli",

        "Unterm Dirndl wird gejodelt",
        "Unterm Röckchen stößt das Böckchen",
        "Urlaubsgrüße aus dem Unterhöschen",
        "Urlaubsreport - Worüber Reiseleiter nicht sprechen dürfen",

        "Und täglich schmerzt mein Rüssel mir",
        "Uranus is huge",

        "Vanilleeis und Pettingcoats",

        "V for Vagina",
        "Voll In' Arsch 1 bis 6",

        "Waidmannsheil im Spitzenhöschen",

        "Wixblumenstrauß",
        "Wunderbare Welt des Schwellsaft",
        "Wicki und die starken Schwängel",
        "Wichs-Men",

        "xXx",
        "XXX-Men",
        "XXX-Men Ejakulation",

        "Yellow Sexmachine",


        "Zucht der Karibik: Hairy Man's Chest",
        "Zum Löten freigegeben",

        "Ach jodel mir noch einen - Stoßtrupp {target} bläst zum Angriff",
        "{target}s unheimliche Begegnung mit der Reizwäsche",
        "{target} in Wonderland",
        "{target} - Wild und unersättlich",
        "{target} - wie ein Blatt auf nackter Haut",
        "{target} - Zur Liebe geboren",
        "Eine Armee {target}",
        "Auch {target} badet manchmal nackt",
        "Auch {target} zieht ihr Höschen aus",
        "{target}, die Unkeusche",
        "{target}'s nächtliche Freuden",
        "{target} - im Reich der Sinnlichkeit",
        "{target}, der Pechvogel",
        "{target} - sündig und süß",
        "{target} and Sex - Die Nackten und die Perversen",
        "{target}, sein Kolben läuft auch ohne Diesel",
        "{target}s Tante nackt",
        "{target}s Nichten",
        "Cream - {target}-Report",
        "{target} - die Anhalterin",
        "{target} und die lüsternen Mädchen von Porno Hill",
        "Ein Doppeldecker für {target}",
        "{target} und seine Gespielinnen",
        "{target} - Eine Frau lebt ihre Träume",
        "{target} und seine Gespielinnen",
        "{target} 77 - La Marge",
        "{target} - Alle Lüste dieser Welt",
        "{target} - Dein wilder Erdbeermund",
        "{target} - Garten der Liebe",
        "{target} geht nach Cannes",
        "{target} - Im Teufelskreis der Leidenschaft",
        "{target} - Insel ohne Tabus",
        "{target} - Sinnlichkeit hat tausend Namen",
        "{target} in Afrika",
        "{target} in Tibet",
        "{target} in Venedig",
        "{target} Freundin",
        "{target} Geheimnis",
        "{target} Zauber",
        "{target} heißer Sommer",
        "Erotic Adventures of {target}",
        "Die erotischen Abenteuer von {target}",
        "{target} und der Mann für alles",
        "{target} - Die Sexsklavin des Cäsar",
        "{target} - Schande der Galaxis",
        "{target} - blutjung und unbefriedigt",
        "Geheime Perversionen der {target}",
        "Graf {target} und seine Nichten",
        "Graf {target} bläst zum Zapfenstreich",
        "Graf {target} und die liebesdurstigen Töchter",
        "Graf {target} und seine Mädchen",
        "Gräfin {target} Liebestempel",
        "{target}, die Fremde, kam nackt",
        "{target} - Haus ohne Männer",
        "Hey {target}, ich brauch mehr Schlaf, auf ins blaukarierte Himmelbett",
        "Inspektor {target} - Der beste Mann von Interpo",
        "Die intimen Momente der {target}",
        "{target}, das liebestolle Kätzchen",
        "{target} Mutzenbacher 2. Teil - Meine 365 Liebhaber",
        "{target} Mutzenbacher - Mein Leben für die Liebe",
        "Junge Lady {target}",
        "{target}, grausame Leidenschaften",
        "{target} - Lustschreie hinter Klostermauern",
        "{target} und Juliette",
        "{target} - Die nackte Zarin",
        "{target} - alle brauchen Liebe",
        "Komm auf die Couch, {target}",
        "{target} - Zwischen Schmach und Liebe",
        "Liebesgrüße aus der Lederhose 6. Teil - Eine Mutter namens {target}",
        "Die Liebesschule der {target}",
        "{target} bläst zum Wahlkampf",
        "{target} am Scheideweg",
        "Madame {target} und ihre Gazellen",
        "Madame {target} und ihre ganz teuren Mädchen",
        "Das Mädchen {target}",
        "{target} - Vom Teufel besessen",
        "{target} - Geheimste Leidenschaften",
        "{target} - Heiß wie ein Vulkan",
        "{target} - Im Paradies der Sinnlichkeit",
        "{target} - Kaiserin und Hure",
        "{target} - Liebesclub der Unersättlichen",
        "{target} - mein heißer Schoß",
        "{target} oder Die Sache mit dem Dreieck",
        "{target} - meine wilden Freuden",
        "{target} - Erotische Sehnsüchte",
        "{target} - Schulmädchen reif für die Liebe",
        "Die Neffen des {target}",
        "{target} - Verbotene Erotik",
        "{target}: Das Wunder der Liebe",
        "{target}: Deine Frau - das unbekannte Wesen",
        "{target}, der Pflaumenpflücker",
        "{target} und die nackte Welle",
        "{target} - das süße Früchtchen",
        "{target} - Einmal Himmel und zurück",
        "{target} - die schmutzige Jungfrau",
        "{target} - Der Potenzprotz",
        "Professor {target} Liebesschule",
        "Professor {target} und seine Vögelein",
        "Der Ritt der Lady {target}",
        "Ritter {target} muß mal wieder",
        "{target} und seine lüsternen Mädchen",
        "{target} und seine wilden Sklavinnen",
        "{target}, der tolle Stier",
        "{target} - heiße Körper",
        "{target}s Liebesreport in drei Dimensionen",
        "{target} - heiß wie ein Vulkan",
        "Der scharfe {target} - Die bumsfidelen Abenteuer einer jungen Ehe",
        "Die Story von {target}",
        "Der Teufel in Miss {target}",
        "Teufelslust mit {target}",
        "Was geschah wirklich mit Miss {target}?",
        "Wilde {target} im Paradies der Lust",
        "Yellow {target}",
        "{target} - Das sechste Gebot",
        "{target} - Spiel mir das Lied der Wollust",
        "{target} und seine lüsternen Mädchen",

        "{target} im Ständerland",
        "{target}, die Nicht-mehr-Jungfrau",

        "{target} im Land der geilen Böcke",
        "{target}, die Dildojägerin",

        "Das Todessperma des Dr. {target}",
        "Das Wunder im {target}",
        "Drei Schwengel für {target}",

        "{target} mit den Penishänden",

        "Gaywatch, Die Riesenschwänze von {target}",

        "Im Wald und auf der {target}",
        "In {target}",
        "{target} und der Gefangene von Arschpackan",
        "{target} und der Stab der Steifen",
        "{target} und die Kammer des Schleckens",
        "{target} und der Feuerfick",
        "{target} und der Orgasmus des Phoenix (erscheint 2007)",
        "{target} und der Vollblutfick (erscheint noch später)",

        "{target} the Raper",
        "{target} - Casino Anal",
        "{target} - Goldficker",
        "{target} - Der Arsch ist nicht genug",
        "{target} - Der Mann mit dem goldenen Schwanz",
        "{target} - Im Angesicht des Kotes",
        "{target} - Moonshaver",
        "{target} - Der Spion mit dem ich Liebe machte",
        "Kapitän {target} und seine geilen Piraten",
        "{target} zum Frühstück",
        "{target} allein im Puff",
        "King {target} und die blonde Frau",
        "Lawrence von {target}",
        "Mad {target} auf Tinas Donnerkuppeln",
        "Mad Maxxx auf {target}s Donnerkuppeln",
        "{target} mag die Lena",
        "Maria mag die {target}",
        "{target}, fick mich ins Koma",
        "Oma {target} \"98\" fickgeil und nicht tot zukriegen",
        "{target} Geil! Angelurlaub am Analsee",
        "{target} auf Karl-Heinz",
        "Pipi auf {target}",
        "{target} im Puller-Puller-Land",
        "{target}, der Puffbesitzer",
        "{target} und seine sieben Glocken",
        "{target} - König der Stecher",
        "{target} und der Einöli",
        "Scheidi und der {target}",
        "{target} und die sieben Geilen",
        "Shaving Private {target}",
        "Shaving {target}'s Privates",
        "Sklave {target} und der geile Meister Leder",
        "Sklave Pupsmuckel und der geile Meister {target}",
        "{target} und die sieben Bukkakezwerge",
        "Spermboat {target}",
        "{target} Arschkopf",
        "{target} und die starken Schwängel",
        "Dieser Graf {target} kommt echt oft",
    ]
