# Description:
#   Such porn, much wow
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   hubot porn me - Needs porntitle
#
# Author:
#   Johnny Deep


module.exports = (robot) ->
  robot.respond /porn me/i, (msg) ->
    porn_title = msg.random porn_responses
    porn_title = porn_title.replace("{target}", msg.message.user.name.capitalize())

    msg.send porn_title


porn_responses = [
        "101 Acts of Love - Der Weg zur sexuellen Freiheit",
        "11.000 Ruten",
        "12 Schwedinnen in Afrika",
        "2 x 2 im Himmelbett",
        "2001 Orgien im Weltraum",
        "69 Liebesspiele",
        "69 - Vorspiel zur Ekstase",

        "A Portrait of Christy",
        "Abarten der körperlichen Liebe",
        "Ach, blas mir doch mal einen Marsch",
        "Ach jodel mir noch einen - Stoßtrupp Venus bläst zum Angriff",
        "Act of Revenge",
        "Adultery",
        "Adventures of Mikki Finn",
        "Africa-Erotica",
        "Afternoon - Stunden der Leidenschaft",
        "Alfreds unheimliche Begegnung mit der Reizwäsche",
        "Alice in Wonderland",
        "Alice - Wild und unersättlich",
        "All The Right Motions",
        "Alle Kätzchen naschen gern",
        "Alpenglühn im Dirndlrock",
        "Als die Frauen noch Schwänze hatten",
        "Als im P... das Licht ausging",
        "Das älteste Gewerbe",
        "Amanda Lear - Follow me",
        "Anatomie des Liebesaktes",
        "Die andere Seite der Sünde",
        "Andrea",
        "Andrea - wie ein Blatt auf nackter Haut",
        "Andy Warhols Dracula",
        "Angelina - von allen begehrt",
        "Animal Crimes",
        "Annie Belle - Zur Liebe geboren",
        "Aphrodite - Im Wendekreis der Begierde",
        "Eine Armee Gretchen",
        "Ars amandi - Die Kunst der Liebe",
        "Arschibald, der Porno-Butler",
        "Art of Desire",
        "Astrologie und Sexualität - Horoskope der Liebe",
        "Attraction",
        "Attraktionen aus aller Welt",
        "Au-Pair-Girls",
        "Auch Engel baden manchmal nackt",
        "Auch Fummeln will gelernt sein",
        "Auch Ninotschka zieht ihr Höschen aus",
        "Auf der Alm, da gibt's koa Sünd' (1974)",
        "Auf und nieder - ich könnt schon wieder",
        "Aufruhr im Frauengefängnis",
        "Augen der Nacht",
        "Aus dem Tagebuch einer Siebzehnjährigen",
        "Die Auto-Nummer - Sex auf Rädern",

        "Akte Wixx",
        "Al Caporno",
        "Alarm im Darm",
        "Alice im Ständerland",
        "Aliens vs. Penetrator",
        "American Fistory XXX",
        "American Fickboxer",
        "Analdin und die wunde Schlampe",
        "Analgeddon",
        "Anal Total",
        "Analstufe Rot",
        "Analritter 2 - Heute wird eingedost",
        "Andere Länder, andere Titten",
        "Animal Farm - Jetzt ficken wir Tiere",
        "Arielle, die Nicht-mehr-Jungfrau",
        "Auf den Highway sind die Schlampen los",
        "Auf der Liege der außergewöhnlichen Gentlemen",
        "Aufstand in der Lederhose",
        "Axel Fick und Obel Wichs",

        "Baby Cat",
        "Babystrich im Sperrbezirk",
        "Bacchanale - Die totale Erotik",
        "Backlash",
        "Bademeister-Report",
        "Banana Airlines - Die verrückteste Lustlinie der Welt",
        "Barbara, die Unkeusche",
        "Baron Porno's nächtliche Freuden",
        "Beach Fever",
        "Beatrice - im Reich der Sinnlichkeit",
        "Begierde auf Abwegen",
        "Begierde der Unschuld",
        "Bei Anruf Liebe",
        "Beichte einer Liebestollen",
        "Beim Jodeln juckt die Lederhose",
        "Benny, der Pechvogel",
        "Die betörende Nachbarin",
        "Bett-Kanonen",
        "Bettgeknister - Sexgeflüster",
        "Bettkarriere (1971)",
        "Bibi - sündig und süß",
        "Black Cats (1973)",
        "Black Emanuelle",
        "Black Emanuelle 2. Teil",
        "Black Emanuelle - Stunden wilder Lust",
        "Black Magic (1987)",
        "Black Sands - Am Anfang war die Liebe",
        "Die Blonde mit dem süßen Busen",
        "Blonde Unschuld",
        "Blue Movies",
        "Blumen ohne Duft",
        "Blutjunge Mädchen - hemmungslos",
        "Blutjunge Masseusen",
        "Blutjunge Unschuld",
        "Blutjunge Verführerinnen - 3. Teil",
        "Blutjunge Verführerinnen - 2. Teil",
        "Blutjunge Verführerinnen",
        "Body of Influence",
        "Bohr weiter, Kumpel",
        "Bombenstimmung im Hauptquartier",
        "Bora Bora",
        "Born For Love",
        "Boys and Sex - Die Nackten und die Perversen",
        "Die Bruchpiloten vom Königssee",
        "Brummi, sein Kolben läuft auch ohne Diesel",
        "Das Bullenkloster",
        "Das bumsfidele Heiratsbüro",
        "Die bumsfidelen Mädchen vom Birkenhof",
        "Die Bumsköpfe",
        "Der Bumsladen-Boß",
        "Bush Pilots",
        "Butterfly",

        "Bambi im Land der geilen Böcke",
        "Bananenfick in Mosambik",
        "Battlefield Ass",
        "Beischlafes Bruder",
        "Beverly Hills Cock",
        "Big Mama - Speckfalten in Wallung",
        "Bitch - Der Fickdoktor",
        "Black Cock Down",
        "Blair Bitch Project",
        "Blowing for Columbine",
        "Bonnie in Clyde",
        "Boschwanza",
        "Baffy, die Dildojägerin",
        "Deutschland sucht den Pornstar",
        "Bienenstich im Lesbennest",

        "Caged Women",
        "Caligula und Messalina",
        "Call-Girl-Report",
        "Casanova '70",
        "Casanova & Co.",
        "Cat & Mouse",
        "Catch Your Dreams",
        "Catherine",
        "Catherine & Co.",
        "Ceylon my love",
        "Chain of Desire",
        "Charleys Tante nackt",
        "Charlys Nichten",
        "Chatterbox",
        "Der Chauffeur von Madame",
        "Cinderella - Süß und Sündig",
        "Country Lady",
        "Cream - Schwabing-Report",
        "Cut - Mord vor laufender Kamera",

        "Cockduel",
        "Cocklateral damage",
        "Cockzilla, Ein Riesenschwanz in New York",
        "Chinese Dickstory (1-3)",

        "Die Dame im Bus",
        "Danger Touch",
        "Dangerous Affairs",
        "Dangerous Love - Lust und Begierde",
        "Danish Bedside",
        "Danish Flowers",
        "Danish Movie",
        "Dany - die Anhalterin",
        "Dark Corners",
        "Das gibt es nur im Wilden Westen",
        "Dauernd erregt",
        "Deadly Sins",
        "Decamerone - Abenteuer der Wollust",
        "Deep Throat in Tokyo",
        "Deine Frau betrügt uns",
        "Delikate Spiele",
        "Delta of Venus",
        "Des Satans heiße Katzen",
        "Desideria",
        "Die Deutsche Sex-Partei",
        "Digital Love",
        "Django Nudo und die lüsternen Mädchen von Porno Hill",
        "Donnerwetter! Donnerwetter! Bonifatius Kiesewetter",
        "Ein Doppeldecker für Madame O.",
        "Dornwittchen und Schneeröschen",
        "Down Town - Die nackten Puppen der Unterwelt",
        "Dr. Fummel und seine Gespielinnen",
        "Dr. Jeckel und Miss Hide",
        "Dralle Brüste, steile Schenkel",
        "Dreams of Desire",
        "Drei Arten Liebe",
        "Drei Schwedinnen in Oberbayern",
        "Dreieck der Lust",
        "Dressage",
        "Dressurakt",
        "Drop out - Mysterien blutjunger Mädchen",
        "Drüber, drunter und drauf",
        "Duett im Bett",

        "Das Besteigen der Lämmer",
        "Das fickende Klassenzimmer",
        "Das Sexperiment",
        "Das Todessperma des Dr. Mabumsen",
        "Das Wunder im Bernd",
        "Der Club der roten Fister",
        "Der Herr der Cockringe",
        "Der große Ficktator",
        "Der Name der Hose",
        "Der Mönch mit der Peitsche",
        "Der Pimmel über Berlin",
        "Der Sexorzist",
        "Deutschland sucht den Superficker",
        "Die Fickinger",
        "Die Prinzessin auf der Eichel",
        "Die Unbesteigbaren von hinten geknallt",
        "Die Vögler",
        "Drei Schwengel für Charlie",
        "Dr. Jekyll in Mrs. Hyde",
        "Dornmöschen",
        "Dune der Brüsteplanet",
        "Dickman Begins",
        "Dickman (1+2)",
        "Dickman& Robin",
        "Domina Day",

        "Ehemänner-Report",
        "Ehepaar sucht Gleichgesinntes",
        "Das ehrliche Interview - Die sexuellen Wünsche der Frau von heute",
        "Eine nach der anderen - Laß fummeln, Puppe",
        "Ekstase zwischen Gier und Lust",
        "Elf Tage und elf Nächte",
        "Elisabeth - Eine Frau lebt ihre Träume",
        "Emanuel und seine Gespielinnen",
        "Emanuela",
        "Emanuela 77 - La Marge",
        "Emanuela - Alle Lüste dieser Welt",
        "Emanuela - Dein wilder Erdbeermund",
        "Emanuela - Garten der Liebe",
        "Emanuelle geht nach Cannes",
        "Emanuelle - Im Teufelskreis der Leidenschaft",
        "Emanuelle - Insel ohne Tabus",
        "Emanuelle - Sinnlichkeit hat tausend Namen",
        "Emmanuelle 4",
        "Emmanuelle 5",
        "Emmanuelle 6",
        "Emmanuelle in Afrika",
        "Emmanuelle in Tibet",
        "Emmanuelle in Venedig",
        "Emmanuelles Freundin",
        "Emmanuelles Geheimnis",
        "Emmanuelles Parfüm",
        "Emmanuelles Zauber",
        "Engel aus Eis",
        "Engel sind nackt am schönsten",
        "Er war besonders wertvoll für die Damen - Ein echter Hausfrauenfreund",
        "Erikas heißer Sommer",
        "Eros-Center Hamburg",
        "Erotic Adventures of Robinson Crusoe",
        "Erotic Prison",
        "Erotik am Abgrund",
        "Erotik auf der Schulbank",
        "Erotik im Beruf - Was jeder Personalchef gern verschweigt",
        "Erotik in Fesseln",
        "Erotische Bestien",
        "Erotische Lust",
        "Erotische Spiele im Pool",
        "Die erotischen Abenteuer der drei Musketiere",
        "Die erotischen Abenteuer von Annette Haven",
        "Die erotischen Träume einer Frau",
        "Erste Sehnsucht",
        "Erstes Öffnen junger Lippen",
        "Es war nicht die Nachtigall",
        "Eva Nera",
        "Eva und der Mann für alles",
        "Explosion der Leidenschaften",
        "Extasy",

        "Edward mit den Penishänden",
        "Ein Fuck kommt selten Alleine",
        "Es wird geschluck was in den Mund kommt",
        "Eine für alle, alle in einer",

        "Facts - Kopenhagen-Sex-Report",
        "Fans - Fans - Fans - Runter mit den Pants",
        "Fatale Leidenschaft",
        "Felicity - Sündige Versuchung",
        "Feuchte Träume junger Frauen",
        "Feuer zwischen den Lippen",
        "Fieber unter nackter Haut",
        "Fiktive Intimitäten",
        "Flash Light",
        "Flavia - Die Sexsklavin des Cäsar",
        "Fleischeslust",
        "Flesh and Love - die hungrigen Mädchen",
        "Flesh Gordon - Schande der Galaxis",
        "Flotte Biester auf der Schulbank",
        "Ein flottes Hausmädchen",
        "Flucht in den Tod - The Arrogant",
        "Flying Sex - die kessen Stewardessen",
        "Foltergarten der Sinnlichkeit",
        "Fontäne der Lust",
        "Forbidden Woman",
        "Frank und Eva",
        "Das französische Frühstück",
        "Der französische Salon der Lady O.",
        "Eine Frau für die Nacht",
        "Frau Professor kann's noch besser",
        "Die Frau vom heißen Fluß",
        "Frauen, die für Sex bezahlen",
        "Frauen im Bordell",
        "Frauen im Liebeslager",
        "Frauen ohne Unschuld",
        "Frauengefängnis (1975)",
        "Das Frauenhaus",
        "Freiheit für die Liebe",
        "French Love",
        "Freude am Fliegen",
        "Die Freuden von Bangkok und Pattaya",
        "Der Freudenspender",
        "Frisch, fromm, fröhlich, frei",
        "Frivole Spiele",
        "Das fröhliche Bordell",
        "Die fröhlichen Holzfäller der nickenden Fichten",
        "Früchte der Leidenschaft",
        "Frühreif und liebestoll",
        "Frühreife Betthäschen",
        "Die frühreifen Mädchen",
        "Frühreifen-Report",
        "Frustration",
        "Fuga",
        "Fummeln im Wasser macht immer nasser",
        "Der Fummeltrick der jungen Sally",
        "Fun - süße Früchtchen zum Vernaschen",
        "Funny Boys und Funny Girls (Die amourösen Abenteuer zweier Freunde)",

        "Fäkalschlacht am Analschacht",
        "Feucht und Feuchter 2 - jetzt wirds spritzig",
        "Feuchte Schenkel im Cockpit",
        "Fick-Bonbons - Jetzt wirds feucht im Mund",
        "Fickendes Inferno",
        "Ficket Nemo",
        "Ficki und die starken Männer",
        "Fickhof der Muschitiere",
        "Fist Club",
        "Flesh Gordon",
        "Flucht von Analtraz",
        "Fuck Bill",
        "Fuck me if you can",
        "Fuck off - Im Körper des Feindes",
        "Fummeln im Sturm (1-6)",
        "Fuckzilla",
        "Ficky Mouse - Gay Crazy",

        "Gabriela - blutjung und unbefriedigt",
        "Galerie der Lust",
        "Das Gasthaus zur Wollust",
        "Gaudi in der Lederhose",
        "Gefährliche Leidenschaften",
        "Gefährlicher Sex frühreifer Mädchen",
        "Gefährlicher Sex frühreifer Mädchen II: Höllisch heiße Mädchen",
        "Gefangene Frauen",
        "Geh, zieh dein Dirndl aus",
        "Geheime Lüste blutjunger Mädchen",
        "Geheime Perversionen der Cleopatra",
        "Das geheime Sexualleben des Casanova",
        "Das geheime Sexualleben von Romeo und Julia",
        "Geheimtechniken der Sexualität",
        "Gehetzte Zeugin",
        "Geilermanns Töchter - Wenn Mädchen mündig werden",
        "Gejodelt wird im Unterhöschen",
        "Das gelbe Haus am Pinnasberg",
        "Gelobt sei, was hart macht",
        "Gelüste der Frauen",
        "Die Gelüste des Hieronymus",
        "Die Geschichte der O. - 2. Teil",
        "Die Geschichte der O.",
        "Geschichten hinter Wänden",
        "Gestatten... Vögelein im Dienst",
        "Gier und Leidenschaft",
        "Die Girls vom Jumbo-Jet",
        "Give me Love",
        "Das Glöcklein unterm Himmelbett",
        "Goin' down slow",
        "Die goldene Banane von Bad Porno",
        "Goodbye Emmanuelle",
        "Graf Bobby und seine Nichten",
        "Graf Porno bläst zum Zapfenstreich",
        "Graf Porno und die liebesdurstigen Töchter",
        "Graf Porno und seine Mädchen",
        "Gräfin Frankensteins Liebestempel",
        "Grausames Verlangen",
        "Greta, die Fremde, kam nackt",
        "Greta - Haus ohne Männer",
        "Griechische Feigen",
        "Grimms Märchen von lüsternen Pärchen",
        "Die große Anmache",
        "Die große Ekstase",
        "Grüne Witwen - billig zu haben",
        "Gwendoline",

        "Gaylien - Director's Fuck",
        "Gaywatch, Die Riesenschwänze von Malibu",
        "Gay's Anatomy",

        "Haben Sie Interesse an der Sache?",
        "Hänsel und Gretel verliefen sich im Wald",
        "Hasenjagd 2. Teil",
        "Hasenjagd in Tokio",
        "Hattu Keuschheitsgürtel muttu knabbern",
        "Das Haus der ausgefallenen Wünsche",
        "Haus der Begierde (1983, Frankr.)",
        "Das Haus der geheimen Lüste",
        "Das Haus der verlorenen Mädchen",
        "Das Haus voller Liebesnarren",
        "Hausaufgaben",
        "Hausfrauen-Report 1. Teil: Hausfrauenreport - unglaublich aber wahr",
        "Hausfrauen-Report 2. Teil: Der neue Hausfrauen-Report",
        "Die Hauslehrerin",
        "Heidi-Heida - Teil 1",
        "Heißblütig",
        "Heiße Berührungen",
        "Die heiße Blonde aus dem kühlen Norden",
        "Heiße Bräute auf der Schulbank",
        "Heiße Fingerspiele",
        "Heiße Flut",
        "Heiße Haut im Sommerwind",
        "Heiße Höschen",
        "Heiße Kolleginnen",
        "Heiße Liebe im Wüstensand",
        "Heiße Sehnsucht",
        "Heiße Semesterferien",
        "Heiße Spiele",
        "Heiße Sporen",
        "Der heiße Tod",
        "Die heißen Engel",
        "Die heißen Nächte der Josefine Mutzenbacher",
        "Die heißen Nächte des Caligula",
        "Die heißen Täubchen von Beverly Hills",
        "Heißer als die Sonne",
        "Ein heißer Eislutscher",
        "Heißer Mund auf feuchten Lippen",
        "Heißer Reiz der Sinnlichkeit",
        "Heißer Sex auf Ibiza",
        "Heißer Sex in Bangkok",
        "Heißer Sex in Dänemark",
        "Heißer Sex in Frankreich",
        "Heißes Verlangen blutjunger Mädchen",
        "Die heißeste Frau der Welt",
        "Hell Hole - Inferno der gequälten Dirnen",
        "Helle Stimmen",
        "Helltrain",
        "Hemd hoch oder ich schieße!",
        "Hemmungslos der Lust verfallen",
        "Hemmungslose Erotik",
        "Die Herrenreiterin",
        "Herzflimmern in St. Tropez",
        "Der Hexentöter von Blackmoor",
        "Hey Marie, ich brauch mehr Schlaf, auf ins blaukarierte Himmelbett",
        "High-Society-Club",
        "Hilfe, meine Frau geht wieder zur Schule",
        "Der Himmel drückt ein Auge zu",
        "Hollywood High",
        "Hollywood Hot Pools",
        "Honeymoon in Paradise",
        "Die Hostessen",
        "Hot Cops",
        "Hot Love",
        "Hot Nights",
        "Hot Summer",
        "Das Hotel der heißen Teens",
        "Hotel Eros - intim",
        "Das Hotel für Fremdenverkehr",
        "Hotelzimmer-Report",
        "House of Dreams",
        "Huckepack",
        "Hunger nach Zärtlichkeit",
        "Hurra, die Schwedinnen sind da",

        "Harte Spiele",
        "Hairy Popper und der Gefangene von Arschpackan",
        "Hairy Popper und der Stab der Steifen",
        "Hairy Popper und die Kammer des Schleckens",
        "Hairy Popper und der Feuerfick",
        "Hairy Popper und der Orgasmus des Phoenix (erscheint 2007)",
        "Hairy Popper und der Vollblutfick (erscheint noch später)",
        "Heisse Länder - Dauerständer",
        "Helicoptermann 2 - 'Die Rückkehr des Kreiselfickers'",
        "HELLRASIERT",
        "Herr der Penisringe",
        "Highway to Möpse",
        "Hitchhikers guide to the fucktasy",
        "Hotel Sodom - Analstufe Rot",
        "House of Wixx",
        "Hör mal wer da nagelt",

        "I need - Ich hab's nötig",
        "Ich bin auch nur eine Frau",
        "Ich - Das Abenteuer, heute eine Frau zu sein",
        "Ich fühl' es kommen",
        "Ich schlafe mit meinem Mörder",
        "Ich spüre deine Haut",
        "Ich war ihm hörig (1978)",
        "Il Corpo",
        "Ilsa, die Tigerin",
        "Ilsa - Haremswächterin des Ölscheichs",
        "Im Bett der nackten Schwestern",
        "Im Garten der Lust",
        "Im Gasthaus zum scharfen Hirschen",
        "Im Kloster der heißen Nonnen",
        "Im Liebesgarten",
        "Im Paradies der Lüste",
        "Im Paradies der Nackten",
        "Im Rausch der Wollust",
        "Im Taumel der Erotik",
        "Im tiefen Tal der Superhexen",
        "Imagine",
        "In 80 Betten um die Welt",
        "In der Gewalt der Zombies",
        "In Love - Sex um jeden Preis",
        "Indian Summer",
        "Inferno (1991)",
        "Infrasexum",
        "Insel der Begierde",
        "Insel der grausamen Mädchen",
        "Insel der Lüste",
        "Die Insel der tausend Freuden",
        "Inseraten-Report",
        "Intim-Report",
        "Intime Beichte einer Frau",
        "Das intime Liebesleben von Bunny und Clod",
        "Intime Spiele junger Pärchen",
        "Intime Stunden auf der Schulbank",
        "Intime Stunden der Lust",
        "Die intimen Momente der Madame Claude",
        "Intimo",
        "Die italienische Affäre",
        "Italienische Früchtchen",
        "Italienische Liebesgrüße",

        "I, Fickbot",
        "Ich war jung und brauchte das Geld",
        "Ich weiß wer dich letzen Sommer gefickt hat",
        "Ich weiß noch immer wer dich letzten Sommer gefickt hat",
        "Ich werde immer wissen wer dich letzten Sommer gefickt hat",
        "In 80 Tagen durch ganz Hinterfeld",
        "In einem Loch vor unserer Zeit",
        "Inspektor Clouseau — Der beste Mann von Interpo",
        "Im Land der RaketenSpermer",
        "Im Wald und auf der Heidi 1-3",
        "Im Wald wird hart geknallt",
        "Im Kloster der 1000 Sünden",
        "Independence Gay",
        "In Diana Jones",
        "Inzestbauern vom Rammlerhof",
        "iPop",

        "Jack und Jill entdecken die Lust",
        "Jagd auf Jungfrauen",
        "Jagdzeit für Naschkätzchen",
        "Jill - Satan in Blond",
        "Jodeln is ka Sünd",
        "Josefine, das liebestolle Kätzchen",
        "Josefine Mutzenbacher 2. Teil - Meine 365 Liebhaber",
        "Josefine Mutzenbacher - Mein Leben für die Liebe",
        "Joy of Sex",
        "Julchen & Jettchen - die verliebten Apothekerstöchter",
        "Junge Lady Chatterley",
        "Junge Mädchen mögen's heiß, Hausfrauen noch heißer",
        "Junge Nymphen",
        "Die jungen Ausreißerinnen - Sex-Abenteuer deutscher Mädchen in aller Welt",
        "Jungfrau aus zweiter Hand",
        "Jungfrau von 18 Karat",
        "Jungfrauenreport",
        "Die jüngsten Kätzchen sind die schärfsten",
        "Justine, grausame Leidenschaften",
        "Justine - Lustschreie hinter Klostermauern",
        "Justine und Juliette",

        "Jack the Raper",
        "Jane Blond - Casino Anal",
        "Jane Blond - Goldficker",
        "Jane Blond - Der Arsch ist nicht genug",
        "Jane Blond - Der Mann mit dem goldenen Schwanz",
        "Jane Blond - Im Angesicht des Kotes",
        "Jane Blond - Moonshaver",
        "Jane Blond - Der Spion mit dem ich Liebe machte",
        "Jarhead - Willkommen im Bett",
        "Jeanne d'Arsch",
        "Jetzt bin ich alt und brauch immer noch Geld",
        "Jurassic Porn",

        "Kaffeebraun & nymphoman",
        "Ein Kaktus ist kein Lutschbonbon",
        "Kamasutra - Vollendung der Liebe",
        "Karate, Küsse, blonde Katzen",
        "Karawane der nackten Frauen",
        "Katharina - Die nackte Zarin",
        "Katja - alle brauchen Liebe",
        "Kätzchen zum Vernaschen",
        "Kay - Sinnlicher Sommer",
        "Kesse Teens und irre Typen",
        "Die Keusche",
        "Keyhole - Heißer Sex aus Dänemark",
        "Der kleine Dicke mit dem großen Langen",
        "Die Kleine mit dem süßen Po",
        "Die kleinen englischen Girls in LET'S DO IT (Tun wir's doch)",
        "Die kleinen Scheinheiligen - Klosterschülerinnen-Report",
        "Kohlpiesels Töchter",
        "Komm auf die Couch, Luise",
        "Komm, wir machen Liebe",
        "Kommt her, ihr wilden Schwedinnen",
        "Königin der Nacht",
        "Köpfchen in das Wasser, Schwänzchen in die Höh'",
        "Ein Körper voller Lust",
        "Krankenschwestern-Report",
        "Kreuzberger Liebesnächte",
        "Der Kumpel läßt das Jucken nicht",
        "Der Kurpfuscher und seine fixen Töchter",
        "Kursaison für scharfe Kumpel",

        "Kack ab Baby 2",
        "Kapitän Arsch und seine geilen Piraten",
        "Kaviar zum Frühstück",
        "Kevin allein im Puff",
        "King Dingeling und die blonde Frau",
        "Kompanie Huren 2: Trommelfeuer aus der Sackkanone",
        "König der Mösen",
        "Kuck' mal wer da schluckt!",
        "Kung Fu Fisting",

        "Lady Chatterley Story",
        "Lady Hamilton - Zwischen Schmach und Liebe",
        "Lady of the Orient Express",
        "Lagune der Lust",
        "Laß jucken im Heu",
        "Laß jucken, Kumpel",
        "Laß jucken, Kumpel 3. Teil - Maloche, Bier und Bett",
        "Laß knacken Schätzchen - Gauner der Liebe",
        "Laß laufen Kumpel",
        "Laß uns Doktor spielen",
        "Ein lasterhafter Sommer",
        "Latin Lover",
        "Laura (1975)",
        "Lebendig gefressen",
        "Lehrmädchen Report",
        "Leidenschaftliche Blümchen",
        "Les Baiseuses - Frühreife Verführerinnen",
        "Les Félines - Der Hengst und die Nymphe",
        "Lesbos - Hohe Schule der Liebe",
        "Leslie Abigail - Ich will immer",
        "Let's talk about Sex",
        "Die letzte amerikanische Jungfrau",
        "Libido - Das große Lexikon der Lust",
        "Libido Mania",
        "Libido Mania 2. Teil",
        "Liebe 1 - 1.000",
        "Liebe '80",
        "Liebe am Vormittag",
        "Liebe auf Asphalt",
        "Liebe durch die Autotür",
        "Liebe durch die Hintertür",
        "Liebe gegen Barzahlung",
        "Liebe im Raumschiff Venus",
        "Liebe in drei Dimensionen",
        "Liebe mich",
        "Liebe ohne Stundenplan",
        "Liebe, Triebe, Seitenhiebe",
        "Liebe unter 17",
        "Liebe unterm Lendenschurz",
        "Liebe zwischen Tür und Angel (Vertreterinnen-Report)",
        "Die Liebesengel",
        "Liebesgrüße aus der Lederhose",
        "Liebesgrüße aus der Lederhose III. Teil",
        "Liebesgrüße aus der Lederhose 6. Teil - Eine Mutter namens Waldemar",
        "Liebesgrüße aus der Lederhose VII - Kokosnüsse und Bananen",
        "Liebesgrüße aus der Lederhose IV",
        "Liebesjagd durch sieben Betten",
        "Die Liebeskerze",
        "Die Liebesklinik",
        "Liebeslust in fremden Betten",
        "Liebesmarkt",
        "Liebesmarkt in Dänemark",
        "Die Liebesmuschel",
        "Die Liebesnächte der Madame X",
        "Die Liebesquelle",
        "Die Liebesschule (1984)",
        "Liebesschule blutjunger Mädchen",
        "Die Liebesschule der Josefine Mutzenbacher",
        "Die Liebessklavin",
        "Liebesspiele junger Mädchen",
        "Liebestechnik für Fortgeschrittene",
        "Die Liebestherapie",
        "Liebestoll",
        "Das liebestolle Freudenhaus",
        "Das liebestolle Hospital",
        "Das liebestolle Internat",
        "Die liebestolle Sexboutique",
        "Die liebestollen Apothekerstöchter",
        "Die liebestollen Baronessen",
        "Die liebestollen Hexen",
        "Die liebestollen Lederhosen",
        "Liebesvögel (1979)",
        "Der Liebeszauber",
        "Liebling, Du beißt so gut",
        "Liebling - vergiß die Peitsche nicht",
        "Das liebste Spiel",
        "Linda Lovelace bläst zum Wahlkampf",
        "Lizenz zum Lieben",
        "Löckchen - ein nackter Spatz in fremden Federn",
        "Lockende Nächte - Black and White",
        "Lolita am Scheideweg",
        "Lorenza",
        "Lorna",
        "Love Dreams",
        "Love in Action",
        "Love in Hongkong",
        "Love, Swedish Style",
        "Lover",
        "Das Luder",
        "Lust auf heiße Lippen",
        "Der lüsterne Türke",
        "Die Lüsternen und die Schwestern",
        "Das Lusthaus teuflischer Begierden",
        "Das Lustschloß im Spessart",
        "Lustschrei im Urwald",
        "Lustvoll eine Schlange streicheln",

        "Lass die Enkel zwischen die Schenkel",
        "Lawrence von Analien",
        "Liebling, ich habe die Kinder gefickt",
        "Last Penis Standing",

        "Mache alles mit",
        "Madame Claude und ihre Gazellen",
        "Madame O und ihre ganz teuren Mädchen",
        "Mädchen auf der Matratze",
        "Mädchen auf Stellungssuche - Der Hostessen-Sex-Report",
        "Das Mädchen aus St. Tropez",
        "Die Mädchen der Madame",
        "Mädchen, die am Wege liegen",
        "Mädchen, die nach München kommen",
        "Mädchen, die sich hocharbeiten",
        "Mädchen, die sich selbst bedienen",
        "Mädchen, die sich verkaufen",
        "Mädchen für verbotene Spiele",
        "Mädchen im Nachtverkehr",
        "Mädchen in der Rückenlage",
        "Das Mädchen Julius",
        "Mädchen - jung und lüstern",
        "Das Mädchen mit der heißen Masche",
        "Mädchen mit offenen Lippen",
        "Mädchen nach Mitternacht",
        "Mädchen ohne Männer",
        "Die Mädchen vom Erziehungsheim",
        "Mädchen zwischen Sex und Sünde",
        "Mädchenjagd in St. Pauli",
        "Magdalena - Vom Teufel besessen",
        "Manche mögen's prall",
        "Die mannstollen Weiber",
        "Marias Liebeslabyrinth",
        "Marilyn - Geheimste Leidenschaften",
        "Marilyn - Heiß wie ein Vulkan",
        "Marilyne - Im Paradies der Sinnlichkeit",
        "Masquerade",
        "Mata Hari (1984)",
        "Matratzentango",
        "Mazurka im Bett",
        "Megavixens",
        "Mei Hos' ist in Heidelberg geblieben",
        "Mein Körper will genommen sein",
        "Melody in Love",
        "Melody of Passion",
        "Melvin",
        "Memory of Love",
        "Messalina - Kaiserin und Hure",
        "Mich will jeder",
        "Michaela - Liebesclub der Unersättlichen",
        "Midnight Ladies",
        "Midnight Sounds",
        "Die Minderjährige",
        "Mirage",
        "Miranda (1985)",
        "Mirror Images",
        "Mister Billion Dollar Babies",
        "Mit der Pille um so toller",
        "Mit Rohrstock und Peitsche",
        "Mon Bel Amour",
        "Mondo New York",
        "Monika und die Sechzehnjährigen",
        "Monique - mein heißer Schoß",
        "Monique oder Die Sache mit dem Dreieck",
        "Mr. Happy und sein steifer Freund",
        "Die munteren Sexspiele unserer Nachbarn",
        "Mutti, Mutti, er hat doch gebohrt",
        "Myriam - meine wilden Freuden",
        "Mysterien der Pornographie",

        "Mad Maxxx auf Tinas Donnerkuppeln",
        "Mac Geiler",
        "Mann fickt Hund",
        "Maria mag die Lena",
        "Marry Poppins",
        "Mighty Fucks",
        "Mighty Fucks II - Die Superficker kehren zurück",
        "Moby Fick - Im Arsch des Pottwals",
        "Monstergurken überfallen die Schweiz",
        "Monsters Of Cock - Das Schwanzfestival",

        "Nach Stockholm der Liebe wegen",
        "Der nächste Herr - dieselbe Dame",
        "Die Nacht der wilden Ladies",
        "Die Nächte der Gamiani",
        "Das Nachtlokal zum Silbermond",
        "Nachtschwester müßte man sein",
        "Nackt für eine Nacht",
        "Nackt und heiß auf Mykonos",
        "Nackt und keß am Königssee",
        "Nackt unter Kannibalen",
        "Die nackte Bovary",
        "Das nackte Cello",
        "Die Nackte",
        "Die nackte Gräfin",
        "Das nackte Pokerspiel",
        "Die Nackte von Sados",
        "Die Nackten des Eros",
        "Die nackten Superhexen vom Rio Amore",
        "Nacktes Fleisch",
        "Nadine - Erotische Sehnsüchte",
        "Nana (1970)",
        "Nathalie - Schulmädchen reif für die Liebe",
        "Necronomicon - Geträumte Sünden",
        "Die Neffen des Herrn General",
        "Nero - und die Huren des römischen Reiches",
        "Neue Spiele für Liebestolle",
        "Das neugierige Weib",
        "New York Nights",
        "New York's Finest",
        "Nicht zugelassen",
        "Die Nichten der Frau Oberst - 2. Teil Mein Bett ist meine Burg",
        "Die Nichten der Frau Oberst (1968)",
        "Die Nichten der Frau Oberst (1979)",
        "Night Crimes",
        "Night Fire",
        "Night Trips",
        "Night Trips - Teil 2",
        "No Time for Love",
        "Die Nonne und das Biest",
        "Die Nonne von Verona",
        "Die Nonnen von Clichy",
        "Nonstop-Sexshow",
        "Norma - Verbotene Erotik",
        "Null Null Sex",
        "Nur für Erwachsene (1970)",
        "Die Nutte von 18 Karat - Das Lustjuwel",
        "Die Nymphomanin",

        "Nackt Zerhackt und Angekackt",
        "Neues vom Sündenhof",
        "Never fuck alone",

        "Ob Dirndl oder Lederhos', gejodelt wird ganz wild drauflos",
        "Oben ohne, unten Jeans",
        "Oben ohne - unten nix",
        "Obszönitäten",
        "Ohne Gnade - Schätzchen",
        "Oktoberfest - da kann man fest...",
        "One-Sided Passion",
        "Operation mißlungen - Patient lebt",
        "Die Orgien der Cleopatra",
        "Der Ostfriesen-Report: O mei, haben die Ostfriesen Riesen",
        "Oswalt Kolle: Das Wunder der Liebe",
        "Oswalt Kolle: Deine Frau - das unbekannte Wesen",
        "Otto, der Pflaumenpflücker",
        "Otto und die nackte Welle",

        "Oma, fick mich ins Koma",
        "Oma Rose \"98\" fickgeil und nicht tot zukriegen",
        "One Night in Bangckock",
        "One Night in Paris",
        "One Night in Rüsseldorf",
        "Operation Delta Fick I- III",
        "Oral! Oral! Oral!",

        "Papa",
        "Paprika - Ein Leben für die Liebe",
        "Paragraph 218 - Wir haben abgetrieben, Herr Staatsanwalt",
        "Parapsycho - Spektrum der Angst",
        "Paris Intim",
        "Paris intim 2. Teil",
        "Paris intim 3. Teil",
        "Paris intim - 4. Teil",
        "Partnertausch im Liebesrausch",
        "Party Doll",
        "Patricia - das süße Früchtchen",
        "Patricia - Einmal Himmel und zurück",
        "Penny - die schmutzige Jungfrau",
        "Pension zur freien Liebe",
        "Percy - Der Potenzprotz",
        "Perfect Timing - Die total verrückte Clique",
        "Perfekt in allen Stellungen",
        "Perfektion der Liebe",
        "Perrak",
        "Personal Service",
        "Der Pfaffenspiegel",
        "Phoenix - Lust und Schmerz",
        "Pistolen-Jenny - Kanonen unter heißen Röcken",
        "Play Love - ein Alphabet erotischer Möglichkeiten",
        "Popcorn und Himbeereis",
        "Poppea, die Hure von Rom - Messalina II",
        "Poppea - Die Kaiserin der Gladiatoren",
        "Porno Baby",
        "Der Porno-Graf von Schweden",
        "Das Porno-Haus von Amsterdam",
        "Porno Motel",
        "Porno-Reise zur Sex-Göttin",
        "Porno zwischen Sex und Sünde",
        "Pornografie illegal",
        "Pornografie in Dänemark (Zur Sache Kätzchen)",
        "Pornografie in Fesseln",
        "Pornographie ohne Maske",
        "Pornographische Aufnahmen",
        "Der Pornokiller",
        "Die Pornoschwestern",
        "Pornospiele mit Stock und Peitsche",
        "Positionen - Variationen",
        "Priester, du sollst nicht ohne Liebe leben",
        "Privatclub für intime Spiele",
        "Professor Bumskes Liebesschule",
        "Professor Lust und seine Vögelein",
        "Prostitution International",
        "Pudelnackt in Oberbayern",
        "Pussy Talk",
        "Pussycat Syndrom",

        "Penispiraten auf Rektalrandale",
        "Per Anhalter durch den Analfick",
        "Peterchens Wichsfahrt",
        "Petri Geil! Angelurlaub am Analsee",
        "Pipi auf Karl-Heinz",
        "Pipi im Puller-Puller-Land",
        "Pissing in Action",
        "Pulp Fickschön",
        "Popeye, der Puffbesitzer",
        "Porn Wars Periode I - Die dunkelbraune Bedrohung",
        "Porn Wars Periode II - Anschiss der Klokrieger",
        "Porn Wars Periode III - Die Rache der Spermien",
        "Porn Wars Periode IV - Ein neuer Harem",
        "Porn Wars Periode V - Das Spermium schlägt zurück",
        "Porn Wars Periode VI - Die Rückkehr der Analritter",
        "Pornstar",

        "Quellen erotischer Lust",

        "Quasimodo und seine sieben Glocken",

        "Rache aus Leidenschaft",
        "Die Rache der Katzenfrauen",
        "Die Rache der Ostfriesen",
        "Ran an die hübsche Paukerin",
        "Randy - Die Sex-Abenteuer des Sylvester Stallone",
        "Rasputin - Orgien am Zarenhof",
        "Das Rasthaus zur sex-ten Glückseligkeit",
        "Rat' mal, wer heut bei uns schläft...?",
        "Reifeprüfung auf der Schulbank",
        "Reitet das rosarote Pferdchen",
        "Die Reitschule der Madame O",
        "Report der Erotik",
        "Ring der Begierde",
        "Der Ritt der Lady Godiva",
        "Ritter Orgas muß mal wieder",
        "Robin Hood und seine lüsternen Mädchen",
        "Robinson und seine wilden Sklavinnen",
        "Robotrix",
        "Romeo, der tolle Stier",
        "Rosalie - heiße Körper",
        "Rosemaries Liebesreport in drei Dimensionen",
        "Roxy",
        "Ruckzuck im Walde",

        "Rate mal wer beim Essen kommt",
        "Reinstecke Fuchs",
        "Rex Dildo - Arschalarm auf der Akropolis",
        "Robin Cock - König der Stecher",
        "RoboCock",
        "Roundhouse Fick - Chuck im Rausch der Leidenschaft",

        "Saint Tropez Vice",
        "Sally - heiß wie ein Vulkan",
        "Saturday Night Special",
        "Savage Island",
        "Savannah - Erotik vor Gericht",
        "Scandalosa Gilda",
        "Schamlose Angela",
        "Schamlose Spiele der Leidenschaft",
        "Scharfe Girls auf Achse",
        "Der scharfe Heinrich - Die bumsfidelen Abenteuer einer jungen Ehe",
        "Scharfe Katzen der Lust",
        "Die scharfen Mädel aus dem Edelbordell",
        "Schicke deinen Teufel in meine heiße Hölle",
        "Das Schiff der liebestollen Frauen",
        "Das Schiff der nackten wilden Mädchen",
        "Schinken mit Ei",
        "Schizophrenia",
        "Das Schloß der blauen Vögel",
        "Schlüsselloch-Report",
        "School for Sex - Rund ums Bett",
        "Das Schreckens-Kommando",
        "Schrei nach Lust (Liebe als Köder)",
        "Schulmädchen lieben heiß",
        "Schulmädchen - Reif für die Liebe",
        "Schulmädchen-Report 1.Teil: Was Eltern nicht für möglich halten",
        "Schulmädchen-Report 10. Teil: Irgendwann fängt jede an",
        "Schulmädchen-Report 11. Teil: Probieren geht über Studieren",
        "Schulmädchen-Report 12. Teil: Wenn das die Mammi wüßte/Junge Mädchen brauchen Liebe",
        "Schulmädchen-Report 13. Teil: Vergiß beim Sex die Liebe nicht",
        "Schulmädchen-Report 2. Teil: Was Eltern den Schlaf raubt",
        "Schulmädchen-Report 3. Teil: Was Eltern nicht mal ahnen",
        "Schulmädchen-Report 4. Teil: Was Eltern oft verzweifeln läßt",
        "Schulmädchen-Report 5. Teil: Was Eltern wirklich wissen sollten",
        "Schulmädchen-Report 6. Teil: Was Eltern gern vertuschen möchten",
        "Schulmädchen-Report 7. Teil: Doch das Herz muß dabei sein",
        "Schulmädchen-Report 8. Teil: Was Eltern nie erfahren dürfen",
        "Schulmädchen-Report 9. Teil: Reifeprüfung vor dem Abitur",
        "Die Schulmädchen vom Treffpunkt Zoo",
        "Schwabinger Girls",
        "Schwarze Aphrodite",
        "Der schwarze Leib der Tarantel",
        "Die schwarze Nymphomanin 2. Teil",
        "Die schwarze Nymphomanin",
        "Schwedenmädel in Paris",
        "Schwedischer Sommerwind",
        "Schwer erziehbare Mädchen",
        "Die Schwestern (Sklavinnen der Erotik)",
        "Scirocco",
        "Sechs Schwedinnen auf der Alm",
        "Sechs Schwedinnen auf Ibiza",
        "Sechs Schwedinnen hinter Gittern",
        "Sechs Schwedinnen im Pensionat",
        "Sechs Schwedinnen von der Tankstelle",
        "Secret Games",
        "Secret Games 3",
        "Secret Games II - Heiße Hostessen",
        "Secrets",
        "Sehnsucht (1977)",
        "Seid nett aufeinander",
        "Sekretärinnen-Report",
        "Sekretärinnen-Report 2. Teil",
        "Semmel, Wurst und Birkenwasser",
        "Sex (1993)",
        "Sex 2",
        "Die Sex-Abenteuer der drei Musketiere",
        "Sex-Abitur 2. Teil",
        "Das Sex-Abitur - Heiße Liebe in Blue Jeans",
        "Sex and Drive",
        "Sex and Life",
        "Sex and Life 2. Teil",
        "Sex Appeal",
        "Sex-Export aus Amsterdam",
        "Sex-Export aus Amsterdam 2. Teil",
        "Sex hinter geschlossenen Türen",
        "Sex im Neonlicht",
        "Sex kreuz und quer",
        "Sex mit den Stars",
        "Sex pervers",
        "Sex-Roulette",
        "Sex-Saison in Las Vegas",
        "Sex vor sechs Millionen Jahren",
        "Sex wie Feuer und Eis",
        "Der Sexathlet (Die Frauen stehen bei ihm Schlange)",
        "Der Sexbomber",
        "Die Sexklinik",
        "Sexklub der Triebhaften",
        "Die Sexmaschine",
        "Sexplosiv",
        "Sexpraxis '74",
        "Sexreport blutjunger Mädchen",
        "Sexsaison in Las Vegas",
        "Die Sexsklavinnen von Schloß Porno",
        "Die Sexspelunke von Bangkok",
        "Sexspiele und Ekstasen",
        "Sexual Intent",
        "Sexual Malice",
        "Sexualrausch",
        "Sexy Gang",
        "Sie tötete in Ekstase",
        "Siegfried und das sagenhafte Liebesleben der Nibelungen",
        "Silver Elegance",
        "Silver Sensations",
        "Sins of the Night - Gefährtin der Nacht",
        "Skandal (1976)",
        "Skandalöse Emanuelle - Die Lust am Zuschauen",
        "Skandinavische Lust",
        "Skihaserl-Report",
        "Sklaven des Eros",
        "Sklavenmarkt der weißen Mädchen",
        "Sklavin der Sinnlichkeit",
        "Sklavin der Wollust",
        "Sklavin für einen Sommer",
        "Sklavin in Leder",
        "Die Sklavinnen",
        "Skrupellos (1986)",
        "Skrupellos II",
        "Slip auf Trip",
        "Snow Bunnies - Die lüsternen Betthäschen",
        "Ein Sommer auf dem Lande",
        "Ein Sommer der wilden Liebe",
        "Ein Sommer voller Leidenschaft",
        "Ein Sommer voller Zärtlichkeit (1981)",
        "Sonne, Sand und heiße Schenkel",
        "Sonne, Sylt und kesse Krabben",
        "South Beach Academy",
        "Spielen wir Liebe",
        "Sprechen-flüstern-stöhnen - Michi-no-sex",
        "\"St. Pauli-Nachrichten\" - Thema Nr.1",
        "Stellungen",
        "Stets bereit",
        "Die Story von Joanna",
        "Die Stoßburg",
        "Stoßverkehr",
        "Stoßzeit - Rush Hour",
        "Die Strandbiene",
        "Das Strandhaus",
        "Strange Love",
        "Stranger",
        "Strip Poker",
        "Studentinnen-Report",
        "Stundenplan einer Verführung",
        "Die Stute",
        "Summer Camp",
        "Sünde mit Rabatt",
        "Die Sünden der ganz jungen Mädchen",
        "Das sündige Bett",
        "Die sündige Kleinstadt",
        "Sündige Lippen",
        "Die Superhexe der Liebesinsel",
        "Die Supernacht",
        "Supervixens - Eruption",
        "Das süße Leben der Nonne von Monza",
        "Sweet Sugar",
        "Swingers",
        "Symphonie der Sinnlichkeit",
        "Syrtaki - Erotik ohne Maske",

        "Sauerei auf der Bounty",
        "Schamlos in Seattle",
        "Scheidi und der Einöli",
        "Scheiß am Stil",
        "Schneeflittchen und die sieben Geilen",
        "Schwanz der Vampire",
        "Schwänzel und Gretel",
        "Schwänze & Partner",
        "Schweinchen Fick",
        "SEX AGE 2 -jetzt wird gespritzt",
        "Sexcalibur",
        "Sexy Island - Der Kampf ums nackte Überleben",
        "Sexy Pirates - Hier wird nicht nur in See gestochen",
        "Shaving Private Ryan",
        "Shaving Ryan's Privates",
        "Sieben Tage, sieben Möpse",
        "Sklave Pupsmuckel und der geile Meister Leder",
        "Spermarella und die sieben Bukkakezwerge",
        "Spermboat Willie",
        "Sponge Bob Arschkopf",
        "Spiel mir am Glied mit Kot",
        "Stadt der Engen",
        "Stanley Kuhficks - Cockwork Orange",
        "Starfick - Popisode 1:\"Das Impedium fickt zurück\"",
        "Steven Strings - Shiting",
        "Stoß langsam I- III",
        "Sündbart der Seepfarrer",
        "Swingapur",

        "Tagträume - Erotische Fantasien",
        "Tanz der Sünde",
        "Tänzerinnen für Tanger",
        "Tanzstunden-Report",
        "Tarzoon - Schande des Dschungels",
        "Teenager - ein französischer Internatsreport",
        "Teenager-Report - Die ganz jungen Mädchen",
        "Das Testament",
        "Der Teufel in Miss Jonas",
        "Das Teufelscamp der verlorenen Frauen",
        "Teufelslust mit Myra",
        "Das Teufelsweib",
        "Teuflische Brüste",
        "Die teuflischen Schwestern",
        "The Barlow Affair",
        "The Devils of Monza",
        "The Pleasure - Die Lust",
        "The Smile of the Fox",
        "The Swap",
        "The Swindle",
        "The Takers - Sex-Revolution der Hemmungslosen",
        "The Teenies - Ein College dreht durch",
        "Thinking Big",
        "Das Tier (1968)",
        "Tinto Brass Voyeur",
        "Töchter der Lust",
        "Der Todesjäger",
        "Toilettengeflüster",
        "Die tolldreisten Geschichten - nach Honoré de Balzac",
        "Die tolle Geschichte der C.",
        "Top Model",
        "Das tosende Mädchenpensionat",
        "Das tosende Paradies",
        "Totale Lust",
        "Traue keinem Hausfreund",
        "Träume einer geschiedenen Frau",
        "Träume im Zwielicht",
        "Traumhaus der Erotik",
        "Traumhaus der Sünde - Teil 1",
        "Triebe unter nackter Haut",
        "Triebhaft wie die nackte Lust",
        "Trio der Lust",
        "Die trüben Tassen der Stube 9",
        "Das turboscharfe Spanner-Motel",
        "Türkische Früchte",
        "Der Turm der lebenden Leichen",
        "Tutti Frutti",
        "Two Moon",
        "Der Typ mit dem goldenen Fifi",

        "Texas Chainfuck Massacre",
        "Tatsächlich ... Lesben",
        "The Ass-Team",
        "The Gay after Tomorrow",
        "The Gays's After",
        "The Masturbator",
        "The Oklahoma bumser",
        "The Porn Identity",
        "The Texas Dildo Massacre",
        "The Truman Po",
        "Tokiobordel",
        "Totgefickt am 4. Juli",

        "Die Unbefriedigte",
        "... und Amor sagt O.K. dazu",
        "... und keine Stellung war ihr fremd",
        "... und mehrmals täglich quietschen die Matrazen",
        "... und sie genießen die Liebe",
        "Undercover Heat",
        "Die unersättlichen Spiele der Reichen",
        "Die Unersättlichen von Beverly Hills",
        "Die Unmoralische",
        "Eine unmoralische Frau - Cosi fan tutte",
        "Unmoralische Novizinnen",
        "Unschuldig gefangen",
        "Unsterbliches Verlangen",
        "Unterm Dirndl wird gejodelt",
        "... unterm Holderbusch",
        "Unterm Röckchen stößt das Böckchen",
        "Urlaubsgrüße aus dem Unterhöschen",
        "Urlaubsreport - Worüber Reiseleiter nicht sprechen dürfen",

        "Und täglich schmerzt mein Rüssel mir",
        "Uranus is huge",

        "Vanessa",
        "Vanilleeis und Pettingcoats",
        "Variationen der Pornographie",
        "Venus im Pelz",
        "Verboten (1969)",
        "Verbotene Früchte der Erotik",
        "Verbotene Lust im Sperrbezirk",
        "Verbotene Sexualität",
        "Verbotene Spiele auf der Schulbank",
        "Verbotene Träume - Klassische Erotica aus Opas Kino 1920-1940",
        "Verbotene Zärtlichkeiten (1971)",
        "Verbotene Zärtlichkeiten (1982)",
        "Verführerinnen-Report",
        "Verführerische Versuchung",
        "Verführerische Verwandlung",
        "Verführerischer Sommer",
        "Verführung auf der Schulbank",
        "Verführung einer Nonne",
        "Verführung in der Pause",
        "Verführung in Seide",
        "Vergewaltigt (1976)",
        "Die Vergnügungsspalte",
        "Vernichtende Leidenschaft",
        "Der verrückte Apotheker",
        "Die verrückte Liebesklinik",
        "Ein verrücktes Freudenhaus",
        "Verwirrende Leidenschaft",
        "Viele Gesichter hat der Tod",
        "Die Villa der Unersättlichen",
        "Virgin Witch",
        "Virginia - Verführt zur Liebe",
        "Vögelein, wo steht dein Bett?",
        "Vollgas",
        "Von der Zensur verboten",
        "Vorstadtfrauen - Lustgefühle am Vormittag",
        "Der Voyeur",
        "Vulkan der höllischen Triebe",

        "V for Vagina",
        "Voll In' Arsch 1 bis 6",

        "Wahnsinns-Trip",
        "Waidmannsheil im Spitzenhöschen",
        "Wall Street Blondie - Der Skandal",
        "Was geschah wirklich mit Miss Jonas?",
        "Was Männer nicht für möglich halten",
        "Was Schulmädchen verschweigen",
        "Was treibt die Maus im Badehaus?",
        "Wehe, wenn die Lust uns packt",
        "Weiße Haut auf schwarzem Markt",
        "Weiße Haut und schwarze Schenkel",
        "Wenn bei süßen Teens die Hüllen fallen",
        "Wenn die Hüllen fallen (1962)",
        "Wenn die Hüllen fallen (1966/72)",
        "Wenn die prallen Möpse hüpfen",
        "Wenn Mädchen heiß den Frühling spüren",
        "Wenn Täubchen Federn lassen",
        "Wer tobt denn da im Unterhaus?",
        "What and Why - Sex in Skandinavien",
        "Why?",
        "Wie der nackte Wind des Meeres",
        "Wie man seine Frau verliert und eine Freundin gewinnt",
        "Wild Attraction",
        "Wild und sexy",
        "Wilde Emmanuelle im Paradies der Lust",
        "Wilde Körper",
        "Die wilde Lady",
        "Wilde Orchidee",
        "Wilde Orchidee 2",
        "Wilde Orchidee 3",
        "Wilde Spiele - heiße Mädchen",
        "Wilde Stuten",
        "Die wilden nackten Mädchen",
        "Die wilden Stunden der schönen Mädchen",
        "Wilder Dreier",
        "Wilder Honig",
        "Wilder Sex frühreifer Mädchen - Tagebuch einer Frühreifen",
        "Ein wildes Leben",
        "Wildkatze",
        "Willst du ewig Jungfrau bleiben?",
        "Das Wirtshaus der sündigen Töchter",
        "Wo der Wildbach durch das Höschen rauscht",
        "Woodoo-Baby - Sex und schwarze Magie in der Karibik",
        "WR - Mysterien des Organismus",
        "Wunderland der Pornographie",
        "Der Wüstling",

        "Wixblumenstrauß",
        "Wunderbare Welt des Schwellsaft",
        "Wicki und die starken Schwängel",
        "Wichs- Men",

        "xXx",
        "XXX-Men",
        "XXX-Men 2",
        "XXX-Men -Der letzte stand wieder",
        "XXX-Men Ejakulation",

        "\"X\" - Beim Sex ist alles erlaubt",

        "Yellow Emanuelle",
        "Young Lady Chatterley II",
        "Young Nurses in Love",

        "Yellow Sexmachine",

        "Zandalee - Das sechste Gebot",
        "Zarte Knospen",
        "Zärtlich aber frech wie Oskar",
        "Zärtlich fängt die Liebe an",
        "Zärtliche Versuchung",
        "Ein zärtliches Biest",
        "Zeig mir deins, zeig ich dir meins",
        "Zeig mir, wie man's macht",
        "Zimmermädchen der Lust",
        "Zizi der Größte",
        "Zorro - Spiel mir das Lied der Wollust",
        "Zorro und seine lüsternen Mädchen",
        "Die Zuchtfarm der Sklaven",
        "Zum zweiten Frühstück: Heiße Liebe",
        "Zur Liebe verdammt",
        "Zwei goldige Girls",
        "Zwei Halunken \"stürmen\" Troja",
        "Zwei Halunken im alten Rom",
        "Zwei Kumpel auf der Alm - Liebesgrüße aus der Lederhose II",
        "Zwei Kumpel in Tirol",
        "Zwei Rebläuse auf dem Weg zur Loreley",
        "Zwischen schwarzen Schenkeln",

        "Zucht der Karibik: Hairy Man's Chest",
        "Zum Löten freigegeben",

        "Ach jodel mir noch einen - Stoßtrupp {target} bläst zum Angriff",
        "{target}s unheimliche Begegnung mit der Reizwäsche",
        "{target} in Wonderland",
        "{target} - Wild und unersättlich",
        "{target} - wie ein Blatt auf nackter Haut",
        "{target} - Zur Liebe geboren",
        "Eine Armee {target}",
        "Auch {target} badet manchmal nackt",
        "Auch {target} zieht ihr Höschen aus",
        "{target}, die Unkeusche",
        "{target}'s nächtliche Freuden",
        "{target} - im Reich der Sinnlichkeit",
        "{target}, der Pechvogel",
        "{target} - sündig und süß",
        "{target} and Sex - Die Nackten und die Perversen",
        "{target}, sein Kolben läuft auch ohne Diesel",
        "{target}s Tante nackt",
        "{target}s Nichten",
        "Cream - {target}-Report",
        "{target} - die Anhalterin",
        "{target} und die lüsternen Mädchen von Porno Hill",
        "Ein Doppeldecker für {target}",
        "{target} und seine Gespielinnen",
        "{target} - Eine Frau lebt ihre Träume",
        "{target} und seine Gespielinnen",
        "{target} 77 - La Marge",
        "{target} - Alle Lüste dieser Welt",
        "{target} - Dein wilder Erdbeermund",
        "{target} - Garten der Liebe",
        "{target} geht nach Cannes",
        "{target} - Im Teufelskreis der Leidenschaft",
        "{target} - Insel ohne Tabus",
        "{target} - Sinnlichkeit hat tausend Namen",
        "{target} in Afrika",
        "{target} in Tibet",
        "{target} in Venedig",
        "{target} Freundin",
        "{target} Geheimnis",
        "{target} Zauber",
        "{target} heißer Sommer",
        "Erotic Adventures of {target}",
        "Die erotischen Abenteuer von {target}",
        "{target} und der Mann für alles",
        "{target} - Die Sexsklavin des Cäsar",
        "{target} - Schande der Galaxis",
        "{target} - blutjung und unbefriedigt",
        "Geheime Perversionen der {target}",
        "Graf {target} und seine Nichten",
        "Graf {target} bläst zum Zapfenstreich",
        "Graf {target} und die liebesdurstigen Töchter",
        "Graf {target} und seine Mädchen",
        "Gräfin {target} Liebestempel",
        "{target}, die Fremde, kam nackt",
        "{target} - Haus ohne Männer",
        "Hey {target}, ich brauch mehr Schlaf, auf ins blaukarierte Himmelbett",
        "Inspektor {target} - Der beste Mann von Interpo",
        "Die intimen Momente der {target}",
        "{target}, das liebestolle Kätzchen",
        "{target} Mutzenbacher 2. Teil - Meine 365 Liebhaber",
        "{target} Mutzenbacher - Mein Leben für die Liebe",
        "Junge Lady {target}",
        "{target}, grausame Leidenschaften",
        "{target} - Lustschreie hinter Klostermauern",
        "{target} und Juliette",
        "{target} - Die nackte Zarin",
        "{target} - alle brauchen Liebe",
        "Komm auf die Couch, {target}",
        "{target} - Zwischen Schmach und Liebe",
        "Liebesgrüße aus der Lederhose 6. Teil - Eine Mutter namens {target}",
        "Die Liebesschule der {target}",
        "{target} bläst zum Wahlkampf",
        "{target} am Scheideweg",
        "Madame {target} und ihre Gazellen",
        "Madame {target} und ihre ganz teuren Mädchen",
        "Das Mädchen {target}",
        "{target} - Vom Teufel besessen",
        "{target} - Geheimste Leidenschaften",
        "{target} - Heiß wie ein Vulkan",
        "{target} - Im Paradies der Sinnlichkeit",
        "{target} - Kaiserin und Hure",
        "{target} - Liebesclub der Unersättlichen",
        "{target} - mein heißer Schoß",
        "{target} oder Die Sache mit dem Dreieck",
        "{target} - meine wilden Freuden",
        "{target} - Erotische Sehnsüchte",
        "{target} - Schulmädchen reif für die Liebe",
        "Die Neffen des {target}",
        "{target} - Verbotene Erotik",
        "{target}: Das Wunder der Liebe",
        "{target}: Deine Frau - das unbekannte Wesen",
        "{target}, der Pflaumenpflücker",
        "{target} und die nackte Welle",
        "{target} - das süße Früchtchen",
        "{target} - Einmal Himmel und zurück",
        "{target} - die schmutzige Jungfrau",
        "{target} - Der Potenzprotz",
        "Professor {target} Liebesschule",
        "Professor {target} und seine Vögelein",
        "Der Ritt der Lady {target}",
        "Ritter {target} muß mal wieder",
        "{target} und seine lüsternen Mädchen",
        "{target} und seine wilden Sklavinnen",
        "{target}, der tolle Stier",
        "{target} - heiße Körper",
        "{target}s Liebesreport in drei Dimensionen",
        "{target} - heiß wie ein Vulkan",
        "Der scharfe {target} - Die bumsfidelen Abenteuer einer jungen Ehe",
        "Die Story von {target}",
        "Der Teufel in Miss {target}",
        "Teufelslust mit {target}",
        "Was geschah wirklich mit Miss {target}?",
        "Wilde {target} im Paradies der Lust",
        "Yellow {target}",
        "{target} - Das sechste Gebot",
        "{target} - Spiel mir das Lied der Wollust",
        "{target} und seine lüsternen Mädchen",

        "{target} im Ständerland",
        "{target}, die Nicht-mehr-Jungfrau",

        "{target} im Land der geilen Böcke",
        "{target}, die Dildojägerin",

        "Das Todessperma des Dr. {target}",
        "Das Wunder im {target}",
        "Drei Schwengel für {target}",

        "{target} mit den Penishänden",

        "Gaywatch, Die Riesenschwänze von {target}",

        "Im Wald und auf der {target}",
        "In {target}",
        "{target} und der Gefangene von Arschpackan",
        "{target} und der Stab der Steifen",
        "{target} und die Kammer des Schleckens",
        "{target} und der Feuerfick",
        "{target} und der Orgasmus des Phoenix (erscheint 2007)",
        "{target} und der Vollblutfick (erscheint noch später)",

        "{target} the Raper",
        "{target} - Casino Anal",
        "{target} - Goldficker",
        "{target} - Der Arsch ist nicht genug",
        "{target} - Der Mann mit dem goldenen Schwanz",
        "{target} - Im Angesicht des Kotes",
        "{target} - Moonshaver",
        "{target} - Der Spion mit dem ich Liebe machte",
        "Kapitän {target} und seine geilen Piraten",
        "{target} zum Frühstück",
        "{target} allein im Puff",
        "King {target} und die blonde Frau",
        "Lawrence von {target}",
        "Mad {target} auf Tinas Donnerkuppeln",
        "Mad Maxxx auf {target}s Donnerkuppeln",
        "{target} mag die Lena",
        "Maria mag die {target}",
        "{target}, fick mich ins Koma",
        "Oma {target} \"98\" fickgeil und nicht tot zukriegen",
        "{target} Geil! Angelurlaub am Analsee",
        "{target} auf Karl-Heinz",
        "Pipi auf {target}",
        "{target} im Puller-Puller-Land",
        "{target}, der Puffbesitzer",
        "{target} und seine sieben Glocken",
        "{target} - König der Stecher",
        "{target} und der Einöli",
        "Scheidi und der {target}",
        "{target} und die sieben Geilen",
        "Shaving Private {target}",
        "Shaving {target}'s Privates",
        "Sklave {target} und der geile Meister Leder",
        "Sklave Pupsmuckel und der geile Meister {target}",
        "{target} und die sieben Bukkakezwerge",
        "Spermboat {target}",
        "{target} Arschkopf",
        "{target} und die starken Schwängel",
        "Dieser Graf {target} kommt echt oft",
    ]
